name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    services:
      mysql:
        image: mysql:8.0.26
        env:
          MYSQL_ROOT_PASSWORD: Root@123
          MYSQL_DATABASE: deploydb
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python3 ${{ matrix.python-version }}
      uses: actions/setup-python3@v2
      with:
        python-version: ${{ matrix.python3-version }}
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: python3 manage.py migrate
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: deploydb
        DBUSER: root
        DBPASSWORD: Root@123
        DBHOST: 192.168.1.28
        DBPORT: ${{ job.services.mysql.ports[3306] }}
    - name: Run Tests
      run: |
        python3 manage.py test
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: deploydb
        DBUSER: root
        DBPASSWORD: Root@123
        DBHOST: 192.168.1.28
        DBPORT: ${{ job.services.mysql.ports[3306] }}
